// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHuhgTPSlTFRpFyZ1fE1tXOYreX6Tmsjc',
    appId: '1:884735699672:web:bec98eab0c29b7e69a85ad',
    messagingSenderId: '884735699672',
    projectId: 'reddit-clone-1f936',
    authDomain: 'reddit-clone-1f936.firebaseapp.com',
    storageBucket: 'reddit-clone-1f936.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb8ofG7Gmll4ukRDiiFhWvvchuVb0wNsE',
    appId: '1:884735699672:android:3bc737f301d3abac9a85ad',
    messagingSenderId: '884735699672',
    projectId: 'reddit-clone-1f936',
    storageBucket: 'reddit-clone-1f936.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXZaQHcp9gtTlJSQpOn6Vr05MSlvbzrcU',
    appId: '1:884735699672:ios:afccf43c00a169659a85ad',
    messagingSenderId: '884735699672',
    projectId: 'reddit-clone-1f936',
    storageBucket: 'reddit-clone-1f936.appspot.com',
    iosClientId: '884735699672-fu5ve5arbhdgl1e4epb8n2kgfhm3jigc.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXZaQHcp9gtTlJSQpOn6Vr05MSlvbzrcU',
    appId: '1:884735699672:ios:afccf43c00a169659a85ad',
    messagingSenderId: '884735699672',
    projectId: 'reddit-clone-1f936',
    storageBucket: 'reddit-clone-1f936.appspot.com',
    iosClientId: '884735699672-fu5ve5arbhdgl1e4epb8n2kgfhm3jigc.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
